name: "Sync Tailscale ACLs"
description: "Push changes to Tailscale and run ACL tests in CI"
inputs:
  tailnet:
    description: "Tailnet ID or Name (eg. TCZrp4oabE12CNTRL, example.com, xe.github, tailscale.org.github)"
    required: true
  oidc-client-id:
    description: "Tailscale OIDC Client ID"
    required: true
  oidc-audience:
    description: "Tailscale OIDC Audience"
    required: true
  policy-file:
    description: "Path to policy file"
    required: true
    default: ./policy.hujson
  action:
    description: "Action to take (test/apply)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate OIDC JWT from Github Actions
      id: get_gh_oidc_token
      shell: bash
      run: |
        OIDC_JWT=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${{ inputs.oidc-audience }}" | jq -r '.value')
        echo "::add-mask::$OIDC_JWT"
        echo "jwt=$OIDC_JWT" >> $GITHUB_OUTPUT

    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: 1.25.5
        cache: false

    - name: Gitops pusher
      shell: bash
      env:
        TS_ID_TOKEN: "${{ steps.get_gh_oidc_token.outputs.jwt }}"
        TS_TAILNET: "${{ inputs.tailnet }}"
      run: go run tailscale.com/cmd/gitops-pusher@4c37141ab780dbf6c037bd64fe48ab330441ad06 "--policy-file=${{ inputs.policy-file }}" "${{ inputs.action }}"
