name: "Sync Tailscale ACLs"
description: "Push changes to Tailscale and run ACL tests in CI"
inputs:
  tailnet:
    description: "Tailnet ID or Name (eg. TCZrp4oabE12CNTRL, example.com, xe.github, tailscale.org.github)"
    required: true
  oidc-client-id:
    description: "Tailscale OIDC Client ID"
    required: true
  oidc-audience:
    description: "Tailscale OIDC Audience"
    required: true
  policy-file:
    description: "Path to policy file"
    required: true
    default: ./policy.hujson
  action:
    description: "Action to take (test/apply)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate OIDC JWT from Github Actions
      id: get_gh_oidc_token
      shell: bash
      run: |
        OIDC_JWT=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${{ inputs.oidc-audience }}" | jq -r '.value')
        echo "::add-mask::$OIDC_JWT"
        echo "jwt=$OIDC_JWT" >> $GITHUB_OUTPUT

    - name: Exchange OIDC JWT with a short-lived Tailscale API Key
      id: tailscale_api_key
      shell: bash
      run: |
        RESPONSE=$(curl -X POST https://api.tailscale.com/api/v2/oauth/token-exchange \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "client_id=${{ inputs.oidc-client-id }}" \
          -d "jwt=${{ steps.get_gh_oidc_token.outputs.jwt }}")
        export ACCESS_TOKEN=$(echo $RESPONSE | jq -r '.access_token')
        echo "::add-mask::$ACCESS_TOKEN"
        echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
    
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22.4
        cache: false

    - name: Gitops pusher
      shell: bash
      env:
        TS_API_KEY: "${{ steps.tailscale_api_key.outputs.access_token }}"
        TS_TAILNET: "${{ inputs.tailnet }}"
      run: go run tailscale.com/cmd/gitops-pusher@66aa77416744037baec93206ae212012a2314f83 "--policy-file=${{ inputs.policy-file }}" "${{ inputs.action }}"
