name: "Sync Tailscale ACLs"
description: "Push changes to Tailscale and run ACL tests in CI"
inputs:
  tailnet:
    description: "Tailnet name (eg. example.com, xe.github, tailscale.org.github)"
    required: true
  api-key:
    description: "Tailscale API key"
    required: true
  policy-file:
    description: "Path to policy file"
    required: true
    default: ./policy.hujson
  action:
    description: "Action to take (test/apply)"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    TS_API_KEY: "${{ inputs.api-key }}"
    TS_TAILNET: "${{ inputs.tailnet }}"
  args:
    - "--policy-file=${{ inputs.policy-file }}"
    - "${{ inputs.action }}"
